name: Naukri Automation

on:
  schedule:
    - cron: '30 2,3,8,9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Automation Script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python naukri.py

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: naukri-screenshots
          path: screenshots/
